FROM ubuntu:latest
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y curl python3-dev python3-pip nano tree apt-transport-https tzdata mariadb-client libmariadb3 libmariadb-dev
ENV FLASK_ENV=production
COPY srcPy/ /home/srcPy/
RUN pip3 install -r /home/srcPy/requirenments.txt
CMD [ "/bin/bash" ]
ENTRYPOINT [ "gunicorn", "--bind", "0.0.0.0:9091", "--chdir", "/home/srcPy", "vm_k8s.app:app"]
EXPOSE 9091
